CHDRS  += $(wildcard OpenGL/*.h)
CPPSRC += $(wildcard OpenGL/*.cpp)
CCCSRC += $(wildcard OpenGL/*.c)

CHDRS  += $(wildcard Metal/*.h)
CPPSRC += $(wildcard Metal/*.cpp)
CPPSRC += $(wildcard Metal/*.mm)

include ../src.makefile
include ../lib.makefile
