CHDRS  += $(wildcard OpenGL/*.h)
CPPSRC += $(wildcard OpenGL/*.cpp)
CCCSRC += $(wildcard OpenGL/*.c)

CHDRS  += $(wildcard MTL/*.h)
CPPSRC += $(wildcard MTL/*.cpp)
CPPSRC += $(wildcard MTL/*.mm)

include ../src.makefile
include ../lib.makefile
