CHDRS  += $(wildcard event/*.h)
CPPSRC += $(wildcard event/*.cpp)
CCCSRC += $(wildcard event/*.c)

CHDRS  += $(wildcard layer/*.h)
CPPSRC += $(wildcard layer/*.cpp)
CCCSRC += $(wildcard layer/*.c)

CHDRS  += $(wildcard imgui/*.h)
CPPSRC += $(wildcard imgui/*.cpp)
CPPSRC += $(wildcard imgui/*.mm)
CCCSRC += $(wildcard imgui/*.c)

CHDRS  += $(wildcard renderer/*.h)
CPPSRC += $(wildcard renderer/*.cpp)
CCCSRC += $(wildcard renderer/*.c)

CHDRS  += $(wildcard input/*.h)
CPPSRC += $(wildcard input/*.cpp)
CCCSRC += $(wildcard input/*.c)

CHDRS  += $(wildcard window/*.h)
CPPSRC += $(wildcard window/*.cpp)
CCCSRC += $(wildcard window/*.c)

CHDRS  += $(wildcard util/*.h)
CPPSRC += $(wildcard util/*.cpp)
CCCSRC += $(wildcard util/*.c)

CHDRS  += $(wildcard scene/*.h)
CPPSRC += $(wildcard scene/*.cpp)
CCCSRC += $(wildcard scene/*.c)

CHDRS  += $(wildcard script/*.h)
CPPSRC += $(wildcard script/*.cpp)
CCCSRC += $(wildcard script/*.c)

CHDRS  += $(wildcard application/*.h)
CPPSRC += $(wildcard application/*.cpp)
CPPSRC += $(wildcard application/*.mm)
CCCSRC += $(wildcard application/*.c)

include ../src.makefile
include ../lib.makefile
